hide the cursor after inactivity
manjaro-sway/desktop-settings pull request #165
Opened 2023-10-03 09:10 UTC by l-j-g

not sure how other people feel about this change, but it is an improvement imo

2023-10-03 15:27 UTC, boredland commented
While I like it, we probably should make it configurable.

2023-10-03 19:43 UTC, boredland requested changes
wdyt about just hiding it while typing automatically?

2023-10-03 19:43 UTC, boredland commented on community/sway/etc/sway/definitions
> +seat seat0 hide_cursor 5000
```suggestion
# hide cursor while typing
seat * hide_cursor when-typing enable
```

2023-10-04 01:20 UTC, l-j-g commented
to make it configurable we run into the same issue as the parameters for the sway-idle settings from some months ago. the system configuration is applied first, then the user configuration on top, which means the entire setting would need to be redefined. 

ideally we would set configurable parameters like that at the initialization shell (.config/profile/) and reference them within the sway configuration (is that possible ?, it should be right ?)

i think when typing might be a suitable 'no-config' compromise, ill try it out tonight.

2023-10-04 11:15 UTC, boredland commented
I have been using it with the current state for some days now and quite like it. If users like to opt out, they can override the setting quite easily, so I don't see an issue. And I don't assume users will be annoyed by it anyway, as if you do something mouse-intensive on your machine, it probably will never even hide anyway.

2023-10-04 20:49 UTC, merged

2023-11-23 17:12 UTC, fourpoints commented
This change broke a few things for me, there are cases where I'm holding down the mouse button and press a keyboard button for an action. It was tricky to notice, since the cursor was already hidden during dragging.

Related issue: https://github.com/swaywm/sway/issues/6297

I don't know if it's worth reverting, as I can see it being nice, but I thought I'd mention it in case anyone else has a similar issue.

2023-11-23 17:14 UTC, boredland commented
Ya, for me copy-ing something from a type-hint in vscode intellisense broke - which is annoying too. I guess we should revert it.

2023-11-23 17:16 UTC, boredland commented
instead of reverting we probably should go back to @l-j-g initial proposal of doing it after 5s of inactivity?

2023-12-02 08:19 UTC, fourpoints commented
I've tried the 5 second hide for a few days now without issues, so it seems fine.