Adds ulauncher settings and theme
Manjaro-Sway/desktop-settings pull request #4
Opened 2021-01-22 17:50 UTC by simon-bueler

Signed-off-by: simon-bueler <simon.bueeler@icloud.com>

2021-01-22 19:44 UTC, boredland requested changes
please check if this works with `GDK_BACKEND` set in .profile too, since other applications might profit from that var.

2021-01-22 19:44 UTC, boredland commented on community/sway/etc/sway/definitions
> +set $menu exec GDK_BACKEND=wayland ulauncher --no-window-shadow
couldn't you set "GTK_BACKEND" in the .profile like the other similar configs?
https://github.com/Manjaro-Sway/desktop-settings/blob/9eae1e81164d24405a5aeb5da4451d7108df7beb/community/sway/etc/skel/.profile#L12

2021-01-23 10:48 UTC, boredland commented on community/sway/etc/sway/config.d/98-application-defaults
> +for_window [app_id="ulauncher"] floating enable, border none
```suggestion
for_window [app_id="ulauncher"] floating enable, border none, sticky enable
```

2021-01-23 14:38 UTC, simon-bueler commented on community/sway/etc/sway/definitions
> +set $menu exec GDK_BACKEND=wayland ulauncher --no-window-shadow
Removed GDK_BACKEND=wayland  since it not seem to be necessary

2021-01-23 14:50 UTC, merged